import { DataSource } from 'typeorm';
import { Product } from '../../products/entities/product.entity';
import * as dotenv from 'dotenv';

dotenv.config();

const PRODUCT_SEEDS = [
  {
    name: 'Free Fire 70 Diamonds',
    category: 'game',
    provider: 'Free Fire',
    price: 15000,
    denomination: '70 Diamonds',
    description: 'Top up 70 Diamonds Free Fire langsung ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Free Fire 355 Diamonds',
    category: 'game',
    provider: 'Free Fire',
    price: 65000,
    denomination: '355 Diamonds',
    description: 'Top up 355 Diamonds Free Fire langsung ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Free Fire 720 Diamonds',
    category: 'game',
    provider: 'Free Fire',
    price: 125000,
    denomination: '720 Diamonds',
    description: 'Top up 720 Diamonds Free Fire langsung ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Free Fire 1440 Diamonds',
    category: 'game',
    provider: 'Free Fire',
    price: 245000,
    denomination: '1440 Diamonds',
    description: 'Top up 1440 Diamonds Free Fire langsung ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Mobile Legends 86 Diamonds',
    category: 'game',
    provider: 'Mobile Legends',
    price: 20000,
    denomination: '86 Diamonds',
    description: 'Top up 86 Diamonds Mobile Legends ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Mobile Legends 172 Diamonds',
    category: 'game',
    provider: 'Mobile Legends',
    price: 39000,
    denomination: '172 Diamonds',
    description: 'Top up 172 Diamonds Mobile Legends ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Mobile Legends 257 Diamonds',
    category: 'game',
    provider: 'Mobile Legends',
    price: 58000,
    denomination: '257 Diamonds',
    description: 'Top up 257 Diamonds Mobile Legends ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Mobile Legends 344 Diamonds',
    category: 'game',
    provider: 'Mobile Legends',
    price: 78000,
    denomination: '344 Diamonds',
    description: 'Top up 344 Diamonds Mobile Legends ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'PUBG Mobile 60 UC',
    category: 'game',
    provider: 'PUBG Mobile',
    price: 16000,
    denomination: '60 UC',
    description: 'Top up 60 UC PUBG Mobile instan ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'PUBG Mobile 325 UC',
    category: 'game',
    provider: 'PUBG Mobile',
    price: 79000,
    denomination: '325 UC',
    description: 'Top up 325 UC PUBG Mobile instan ke akun Anda',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Netflix Premium 1 Bulan',
    category: 'streaming',
    provider: 'Netflix',
    price: 54000,
    denomination: '1 Bulan',
    description: 'Akses Netflix Premium 1 bulan, 4K streaming unlimited',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Netflix Premium 3 Bulan',
    category: 'streaming',
    provider: 'Netflix',
    price: 159000,
    denomination: '3 Bulan',
    description: 'Akses Netflix Premium 3 bulan, 4K streaming unlimited',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Spotify Premium 1 Bulan',
    category: 'streaming',
    provider: 'Spotify',
    price: 29000,
    denomination: '1 Bulan',
    description: 'Nikmati musik tanpa iklan dengan Spotify Premium 1 bulan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Spotify Premium 3 Bulan',
    category: 'streaming',
    provider: 'Spotify',
    price: 85000,
    denomination: '3 Bulan',
    description: 'Nikmati musik tanpa iklan dengan Spotify Premium 3 bulan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Disney+ Hotstar 1 Bulan',
    category: 'streaming',
    provider: 'Disney+',
    price: 39000,
    denomination: '1 Bulan',
    description: 'Akses Disney+ Hotstar 1 Bulan untuk film & serial terbaik',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Disney+ Hotstar 3 Bulan',
    category: 'streaming',
    provider: 'Disney+',
    price: 109000,
    denomination: '3 Bulan',
    description: 'Akses Disney+ Hotstar 3 Bulan untuk film & serial terbaik',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'YouTube Premium 1 Bulan',
    category: 'streaming',
    provider: 'YouTube',
    price: 25000,
    denomination: '1 Bulan',
    description: 'Akses YouTube Premium tanpa iklan selama 1 bulan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'YouTube Premium 3 Bulan',
    category: 'streaming',
    provider: 'YouTube',
    price: 72000,
    denomination: '3 Bulan',
    description: 'Akses YouTube Premium tanpa iklan selama 3 bulan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Pulsa Telkomsel 50.000',
    category: 'phone_credit',
    provider: 'Telkomsel',
    price: 51500,
    denomination: 'Rp 50.000',
    description: 'Pulsa Telkomsel Rp 50.000 langsung masuk ke nomor tujuan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Pulsa Telkomsel 100.000',
    category: 'phone_credit',
    provider: 'Telkomsel',
    price: 99000,
    denomination: 'Rp 100.000',
    description: 'Pulsa Telkomsel Rp 100.000 langsung masuk ke nomor tujuan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Pulsa Indosat 50.000',
    category: 'phone_credit',
    provider: 'Indosat',
    price: 51000,
    denomination: 'Rp 50.000',
    description: 'Pulsa Indosat Rp 50.000 langsung masuk ke nomor tujuan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Pulsa Indosat 100.000',
    category: 'phone_credit',
    provider: 'Indosat',
    price: 98500,
    denomination: 'Rp 100.000',
    description: 'Pulsa Indosat Rp 100.000 langsung masuk ke nomor tujuan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Pulsa XL 50.000',
    category: 'phone_credit',
    provider: 'XL',
    price: 51000,
    denomination: 'Rp 50.000',
    description: 'Pulsa XL Rp 50.000 langsung masuk ke nomor tujuan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Pulsa XL 100.000',
    category: 'phone_credit',
    provider: 'XL',
    price: 98500,
    denomination: 'Rp 100.000',
    description: 'Pulsa XL Rp 100.000 langsung masuk ke nomor tujuan',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Paket Data Indosat Freedom 10GB',
    category: 'phone_credit',
    provider: 'Indosat',
    price: 75000,
    denomination: '10 GB',
    description: 'Paket data Indosat Freedom 10GB masa aktif 30 hari',
    imageUrl: null,
    isActive: true,
  },
  {
    name: 'Paket Data Indosat Freedom 20GB',
    category: 'phone_credit',
    provider: 'Indosat',
    price: 135000,
    denomination: '20 GB',
    description: 'Paket data Indosat Freedom 20GB masa aktif 30 hari',
    imageUrl: null,
    isActive: true,
  },
];

export async function seedProducts(dataSource: DataSource): Promise<void> {
  const productRepo = dataSource.getRepository(Product);

  let seededCount = 0;
  for (const seed of PRODUCT_SEEDS) {
    const existing = await productRepo.findOne({
      where: {
        name: seed.name,
        provider: seed.provider,
        denomination: seed.denomination,
      },
    });

    if (!existing) {
      await productRepo.save(seed);
      seededCount++;
    }
  }

  if (seededCount > 0) {
    console.log(`✅ Seeded ${seededCount} new products`);
  } else {
    console.log('Products already fully seeded. Skipping.');
  }
}
